Repository FerrisChat/Server, pull requests merged in 2021-11, with the labels that each got.

#32 Update to Rust 2021
  Cargo.toml
  ferrischat_auth/Cargo.toml
  ferrischat_db/Cargo.toml
  ferrischat_macros/Cargo.toml
  ferrischat_webserver/Cargo.toml
  ferrischat_ws/Cargo.toml
Labels: help wanted

#33 Move the limit < Some(0) check to be the first check
  ferrischat_webserver/src/messages/message_history.rs
Labels: bug, API

#34 Increase max_connections too because why not
  ferrischat_webserver/src/entrypoint.rs
Labels: enhancement, API

#35 Add CORS support
  ferrischat_webserver/Cargo.toml
  ferrischat_webserver/src/entrypoint.rs
Labels: enhancement, API

#44 Sort messages by id
  ferrischat_webserver/src/messages/message_history.rs
Labels: enhancement, API

#47 Add nonce
  ferrischat_webserver/src/messages/delete_message.rs
  ferrischat_webserver/src/messages/edit_message.rs
  ferrischat_webserver/src/messages/get_messages.rs
  ferrischat_webserver/src/messages/message_history.rs
  ferrischat_webserver/src/messages/send_message.rs
Labels: enhancement, API

#50 Add author to message
  ferrischat_webserver/src/messages/delete_message.rs
  ferrischat_webserver/src/messages/edit_message.rs
  ferrischat_webserver/src/messages/get_messages.rs
  ferrischat_webserver/src/messages/message_history.rs
  ferrischat_webserver/src/messages/send_message.rs
Labels: enhancement, API

#57 Add `user` field to `MemberCreate` events
  ferrischat_webserver/src/invites/use_invite.rs
Labels: enhancement, WebSocket

#56 Include guilds in user
  ferrischat_webserver/src/users/get_user.rs
  ferrischat_ws/src/lib.rs
Labels: enhancement, API, WebSocket

#59 Add user objects to IdentifyAccepted
  ferrischat_ws/src/lib.rs
Labels: enhancement, WebSocket

#62 Fix #40
  ferrischat_webserver/src/users/get_user.rs
Labels: enhancement, API

#66 Implement Bots
  Cargo.lock
  ferrischat_webserver/src/auth/bot_get_token.rs
  ferrischat_webserver/src/auth/mod.rs
  ferrischat_webserver/src/entrypoint.rs
  ferrischat_webserver/src/users/bots/create_bot.rs
  ferrischat_webserver/src/users/bots/delete_bot.rs
  ferrischat_webserver/src/users/bots/edit_bot.rs
  ferrischat_webserver/src/users/bots/mod.rs
  ferrischat_webserver/src/users/delete_user.rs
  ferrischat_webserver/src/users/mod.rs
  migrations/20211120162230_add_bots.sql
  migrations/20211120165917_bigint_converion_2.0.sql
  setup.sh
Labels: enhancement, API

#70 Update Error Messages
  Cargo.lock
  ferrischat_macros/src/bigdecimal_to_u128.rs
  ferrischat_macros/src/get_db_or_fail.rs
  ferrischat_macros/src/get_item_id.rs
  ferrischat_macros/src/get_node_id.rs
  ferrischat_webserver/src/auth/bot_get_token.rs
  ferrischat_webserver/src/auth/get_token.rs
  ferrischat_webserver/src/channels/create_channel.rs
  ferrischat_webserver/src/channels/delete_channel.rs
  ferrischat_webserver/src/channels/edit_channel.rs
  ferrischat_webserver/src/channels/get_channel.rs
  ferrischat_webserver/src/guilds/create_guild.rs
  ferrischat_webserver/src/guilds/delete_guild.rs
  ferrischat_webserver/src/guilds/edit_guild.rs
  ferrischat_webserver/src/guilds/get_guild.rs
  ferrischat_webserver/src/guilds/roles/add_member_role.rs
  ferrischat_webserver/src/guilds/roles/create_role.rs
  ferrischat_webserver/src/guilds/roles/delete_role.rs
  ferrischat_webserver/src/guilds/roles/edit_role.rs
  ferrischat_webserver/src/guilds/roles/get_role.rs
  ferrischat_webserver/src/guilds/roles/remove_member_role.rs
  ferrischat_webserver/src/invites/create_invite.rs
  ferrischat_webserver/src/invites/get_guild_invites.rs
  ferrischat_webserver/src/invites/get_invite.rs
  ferrischat_webserver/src/invites/use_invite.rs
  ferrischat_webserver/src/members/delete_member.rs
  ferrischat_webserver/src/members/get_member.rs
  ferrischat_webserver/src/messages/delete_message.rs
  ferrischat_webserver/src/messages/edit_message.rs
  ferrischat_webserver/src/messages/get_messages.rs
  ferrischat_webserver/src/messages/message_history.rs
  ferrischat_webserver/src/messages/send_message.rs
  ferrischat_webserver/src/users/bots/create_bot.rs
  ferrischat_webserver/src/users/bots/delete_bot.rs
  ferrischat_webserver/src/users/bots/edit_bot.rs
  ferrischat_webserver/src/users/create_user.rs
  ferrischat_webserver/src/users/delete_user.rs
  ferrischat_webserver/src/users/edit_user.rs
  ferrischat_webserver/src/users/get_user.rs
  ferrischat_webserver/src/users/verify_user.rs
  ferrischat_ws/src/preload.rs
Labels: enhancement, API, Errors

#71 Implement fetch bots by user
  Cargo.lock
  ferrischat_webserver/src/entrypoint.rs
  ferrischat_webserver/src/users/bots/get_bots_by_user.rs
  ferrischat_webserver/src/users/bots/mod.rs
  ferrischat_webserver/src/users/mod.rs
  ferrischat_webserver/src/users/verify_user.rs
  ferrischat_ws/src/init.rs
Labels: enhancement, API
